image: node:8

pages:
  script:
    - npm install @angular/cli
    - node_modules/@angular/cli/bin/ng build --prod
    - cp -avr ./dist/sicredi-dragons ./public
  artifacts:
    paths:
      - public
  cache:
    paths:
      - node_modules
  only:
    - master
